version: '3.3'
services:
  stirling-pdf:
    container_name: stirling_pdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - ~/.app/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ~/.app/StirlingPDF/extraConfigs:/configs
      - ~/.app/StirlingPDF/customFiles:/customFiles/
      - ~/.app/StirlingPDF/logs:/logs/
      - ~/.app/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=zh_CN