" vim启动自动加载配置文件路径通过|:version|查看              |version| |startup|
" vim命令行启动可通过'-u'选项指定配置文件, 默认配置文件将失效          |man vim|
" 可生成配置文件的符号链接到vim的配置文件目录
"   linux:                                                              |man ln|
"     eg: ln -s /path/to/this/directory /path/to/load/directory
"   windows:                                                            |mklink|
"     eg: mklink /D x:\path\to\this\directory x:\path\to\load\directory
"
"vim --startuptime startuptime.log  #打印启动用时日志
"对某个行为进行分析                                                    |profile|
"   :profile start log.txt
"   :profile func *
"   :profile file *
"   :profile stop 或 退出vim
"重定向命令输出                                                          |redir|
"   :redir >> redir.txt
"   :map
"   :redir END

" 获取路径分隔符及配置文件根目录
let s:pathSeprator= has("win32") ? '\' : '/'
let s:confRoot= expand("<sfile>:h") . s:pathSeprator

if has('win32')
    " 配置文件设置
    " 语言设置
    language en                 "设置vim使用的语言
    "let $LANG='en'             "通过设置环境变量的方式设置语言，影响较大且复杂
    set langmenu=en_US.utf-8
    "echomsg "windows兼容设置启用"
    "windows平台将终端设置为powershell
    "如果是windows则将gvim使用的shell设置为powershell
    "New-Item -Path 'c:\temp\New Folder' -ItemType Directory            #创建文件夹
    "New-Item -Path 'c:\temp\New Folder\newFile.txt' -ItemType File     #创建文件
    "Remove-Item ItemName [-Force]                                      #删除文件或文件夹
    set shell=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    "字体设置
    set guifont=FiraCode_Nerd_Font_Mono:h12:cANSI:qDRAFT
    " 切换GVIM的菜单、工具栏及滚动条的显示 快捷键F2
    set guioptions-=b
	set guioptions-=e
    set guioptions-=T
    set guioptions-=m
    set guioptions-=r
    set guioptions-=L
    set guioptions-=c
    map <silent> <F2> :if &guioptions =~# 'T' <Bar>
        \set guioptions-=b <Bar>
        \set guioptions-=e <Bar>
        \set guioptions-=T <Bar>
        \set guioptions-=m <Bar>
        \set guioptions-=r <Bar>
        \set guioptions-=L <Bar>
        \set guioptions-=c <Bar>
    \else <Bar>
        \set guioptions+=b <Bar>
        \set guioptions+=e <Bar>
        \set guioptions+=T <Bar>
        \set guioptions+=m <Bar>
        \set guioptions+=r <Bar>
        \set guioptions+=L <Bar>
        \set guioptions+=c <Bar>
    \endif<CR>
    "设置firacode 不显示连字的问题[firacode](https://github.com/tonsky/FiraCode/issues/462)
    set renderoptions=type:directx
    "let g:netrw_ftp_cmd= 'c:\Windows\System32\ftp -s:C:\Users\MyUserName\MACHINE'
    "
    "let g:python3_host_prog='C:\Users\yoophoon\AppData\Local\Programs\Python\Python36\python.exe'
    "set pythonthreedll=python36.dll
    set pythonthreehome='C:\Users\yoophoon\AppData\Local\Programs\Python\Python36'
	" 窗体透明度设置及最大化[vimtweak.dll](https://github.com/mattn/vimtweak)
	" let g:vimtweakEnableMaximize= 0
	" let g:vimtweakEnableTopMost= 0
	" call libcallnr(s:confRoot."vimtweak64.dll", "SetAlpha", 100)
else
    ""echomsg "arch兼容设置启用"
    "let g:fcitx5state=system("fcitx5-remote")
    "" 退出插入模式时禁用输入法，并保存状态
    "autocmd InsertLeave * :silent let fcitx5state=system("fcitx5-remote")[0] | silent !fcitx5-remote -c 
    "" 2 表示之前状态打开了输入法，则进入插入模式时启动输入法
    "autocmd InsertEnter * :silent if fcitx5state == 2 | call system("fcitx5-remote -o") | endif 
endif

"=============================================================================="
                                                                                
" motion options
set matchpairs+=<:>				" 匹配尖括号
                                                                                
" 编辑器设置
set nocompatible				" 设置不兼容VI
set belloff=esc					" 取消对应响铃
" set noerrorbells				" 错误响铃
" set novisualbell				" 启用效果 如闪屏, 默认值(boolean): 0

" 主题设置被drewtempelmeyer/palenight.vim插件覆盖
" colorscheme habamax			" 色彩主题, $VIMRUNTIME/color/*.vim
" highlight Normal ctermbg=NONE	" 取消Vim背景颜色以适用终端背景

" 格式化
set textwidth=80				" 单行文本宽度, 超过自动截断换行
" set wrapmargin=10				" 窗口右侧保留区域宽度
" set formatoptions+=t			" 内部格式化选项, 如换行格式	|fo-table||gq|
" set formatexpr				" 格式化表达式
" set formatprg					" 外部格式化程序
" gui窗体设置											|winpos()||winwidth()|
" set columns=80				" 设置初始窗口宽度, gui有效, tui被终端宽度覆盖
" set lines=80					" 设置初始窗口高度, gui有效
" winpos 100 100				" 设置初始窗口位置, gui有效.
" winsize 100 100				" 设置初始窗口尺寸
set showcmd						" 在最后一行显示部分命令, 关闭该选项提升性能
syntax on						" 语法高亮
filetype on						" 文件类型检测
filetype plugin on				" 为特定的文件添加对应的插件

set encoding=utf-8				" Vim内部使用的字符编码
let &fileencoding=&encoding		" 文件的字符编码, 保持和Vim编码一致
let &termencoding=&encoding		" 终端的字符编码, 保持和Vim编码一致
set backspace=indent,eol,start	" 插入模式退格键、删除键、i_CTRL-W、i_CTRL-U的行为
set fillchars+=vert:\┼			" Vim窗口分隔符
highlight VertSplit term=reverse ctermfg=243 ctermbg=NONE guifg=#767676 guibg=#767676
                                                                                
" 搜索
set wrapscan					" 文件内循环搜索 默认开启
set wildmode=longest:list,full  " 补全模式, 怎么进行补全
set wildmenu					" 增强补全功能
set wildoptions=fuzzy,pum		" 命令行补全项来源, 模糊搜索项, 匹配项
set hl=""
set hlsearch					" 高亮搜索结果
set incsearch					" 对按回车前所输入的字符进行搜索即动态搜索
set ignorecase					" 搜索忽略大小写
set showmatch					" 输入括号时短暂的跳转到匹配的括号
set matchtime=5					" 跳转停留的时间, 单位: 十分之一秒

                                                                                
"对齐缩进
set autoindent					" 自动对齐
set smartindent					" 智能对齐
set tabstop=4					" 设置tab键显示宽度, 标准宽度8
set noexpandtab					" 设置tab扩展为空格
set softtabstop=2				" 软制表符宽度, 当达到制表符宽度则替换为制表符
let &shiftwidth=&softtabstop	" 缩进宽度保持与软制表符宽度一致
set shiftround					" 缩进命令对齐缩进宽度, Vim缩进命令宽度默认1'sw'
                                                                                
"显示字符
set list						" 列表模式: 映射特殊字符并显示
set listchars+=space:۰			" 空格显示为۰
set listchars+=tab:→\ ┤			" tab显示为→\ ┤
set conceallevel=0				" 保留高亮语法关键字
" set concealcursor				" 改变鼠标所在行或可视区域的隐藏行为
                                                                                
" 折叠
set foldmethod=indent			" 基于缩进对文本进行折叠
set foldminlines=1				" 最小折叠行数, 可折叠的行数超过该值时产生折叠
function! CustomFoldText()
  let tw= &textwidth > 0 ? &textwidth : 80
  let firstline= substitute(getline(v:foldstart), '\t', repeat(' ', &tabstop), 'g')
  let foldinfo='[' . v:foldstart . '->' . v:foldend . ':' . 
              \(v:foldend - v:foldstart) . '+ ' . 
              \((v:foldend - v:foldstart) > 1 ? 'lines' : 'line') . ']'
  let foldinfoWidth= strdisplaywidth(foldinfo)
  let firstlineWidth= strdisplaywidth(firstline)
  if(firstlineWidth > (tw / 2 + 5))
    let displayline= ''
    for char in firstline
      if(strdisplaywidth(displayline)>= tw / 2 + 5)
        break
      else
        let displayline ..= char
      endif
    endfor
    " return strcharpart(firstline, 0, tw / 2 + 5) . 
    return displayline . repeat(' ', tw / 2 + 10 - strdisplaywidth(displayline))
          \ . repeat(nr2char(0xf09f), 3) . 
          \repeat(' ', tw / 2 - 20 - foldinfoWidth) . foldinfo
  else
    return firstline . repeat(' ', tw / 2 + 10 - firstlineWidth) . 
          \repeat(nr2char(0xf09f), 3) . 
          \repeat(' ', tw / 2 - 20 - foldinfoWidth) . foldinfo
  endif
endfunction
set fillchars+=fold:\ 
set foldtext=CustomFoldText()
  " 自定义foldtext可以, 但是样式是unsupported
  " highlight FoldHighlightSymbol ctermfg=Yellow guifg=Yellow
  " syntax match FoldHighlightSymbol /^.*\zs\ze\s*\[\d\+->\d\+:\d\++\slines\?\]/
  " unsupported feature, [Different highlighting groups for different fold levels]
  " (https://github.com/vim/vim/issues/6172)
  " 测试正则:match Search /^.*\zs\ze\s*\[\d\+->\d\+:\d\++\slines\?\]/
  " let tw= &textwidth > 0 ? &textwidth : 80        [133->157:24+ lines]
  " 配置文件设置                                  [21->63:42+ lines]
                                                                                
" 特殊行列
set signcolumn=number			" 在行号列显示符号
set foldcolumn=0				" 折叠标记列宽度, 默认值为0即关闭功能
set colorcolumn=80				" 高亮指定行, 用于标识指定宽度
set cursorcolumn				" 高亮光标所在列
set nu							" 显示行号
set relativenumber				" 开启相对行号

set cursorline					" 高亮光标所在行
                                                                                
" 状态栏
set ruler						" 显示光标所在位置的行号和列号, 低于'stl'优先级
set laststatus=2				" 状态栏显示策略0:禁止状态栏,1:多窗口显示状态栏
"set statusline=%(%0.100F%m%)%=%(%#ColorColum#\|%)%=%P\ @\ %L,%c/%v%=%S       "被airline设置代替
" set statusline=%#StatuslineNC#%-20.30F%m%#ColorColumn#%(\ >\ 
              \%#StatuslineNC#%)%=%-(%P\ @\ %-20.30L,%c%S%) 

set wrap						" 开启折行显示, 注: 区分textwidth选项
set display+=lastline			" 尽可能多的显示最后一行, 无法显示的则用"@@@"代替
set linebreak					" 单词软换行
" set breakat=					" 导致换行的字符
  " 注意: 区分移动光标所在行位置与移动光标位置的区别
  " 移动光标所在行在屏幕种的位置使用: 
  " |z<CR>|, |zt|			将光标所在行置于窗口顶部, 后者保持光标所在列位置
  " |z.|, |zz|			将光标所在行置于窗口中部, 后者保持光标所在列位置
  " |z-|, |zb|			将光标所在行至于窗口底部, 后者保持光标所在列位置
  " 移动光标位置使用: 
  " H, M, L				将光标移动至窗口顶部、中部、底部
set scrolloff=10				" 光标上方或下方保留的最小行数, 光标无法抵达区域
set novisualbell				" 取消光标闪动
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver25-CursorInsert
set guicursor+=r:hor25-CursorReplace
"set spell spelllang=en,cjk		" 拼写检查

                                                                                
" 编辑信息
set viminfo+=f1					" 保留文件标记
let &viminfofile=s:confRoot.."viminfo"		" 启用viminfo记录文件信息
" 跳转至文件上次退出位置
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | 
				\	exe "normal! g'\"" | 
				\endif
                                                                                
"文件读写
set updatetime=300				" 更新时间间隔
set autoread					" 文件改动后自动读取
set autowrite					" 缓冲区内容自动写入文件, 规则挺多
" set autowriteall				" 与自动写入类似, 但有更多的触发规则
set nobackup					" 保留备份文件, 默认设置
" set backupdir
" set backupskip				" 匹配的文件不进行备份
set writebackup					" 写入备份文件
" 
autocmd InsertLeave,TextChanged,CursorHold * silent! w
autocmd FocusLost,BufLeave * silent! wa

                                                                                
" vim window
"set equalalways       "设置拆分窗口是否相等，默认开始，set noea
"作用于equalalways选项,hor不改变窗口高度ver不改变窗口宽度both宽高由vim决定
"set eadirection "hor" 

                                                                                
" Vim内置插件加载设置
" 第三方插件使用vim-plug管理较为方便
packloadall						" 加载所有'packpath/start'的包

                                                                                
" vim帮助系统
" helpfile选项因为涉及到跨系统文件路径, 在external节设置
set helplang=cn
":helptags ALL					" 生成所有文档的tags文件
":helptoc						" 查看帮助文档目录

                                                                                
"                               loading plugins                                 
                                                                                
" 跨系统操作还是采用vim-plug插件管理vim的插件
call plug#begin()
" [coc.nvim](https://github.com/neoclide/coc.nvim)
" 基于Nodejs和lsp的补全插件
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" [tabular](https://github.com/godlygeek/tabular)
" 轻量化文本排版插件
Plug 'godlygeek/tabular'

" [editorconfig-vim](https://github.com/editorconfig/editorconfig-vim)
" 类似于VSCode的.editorconfig配置
" Plug 'editorconfig/editorconfig-vim'

" [palenight.vim](https://github.com/drewtempelmeyer/palenight.vim)
" 色彩主题
	let g:palenight_color_overrides = {
	\    'black': { 'gui': '#2C323C', "cterm": "NONE", "cterm16": "NONE" },
	\}
Plug 'drewtempelmeyer/palenight.vim'

" [vim-airline](https://github.com/vim-airline/vim-airline)
" 状态栏插件|airline|
	let g:airline#extensions#whitespace#enabled = 0		" 取消空白字符规则检查
	let g:airline_theme="violet"
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" = = = = = = = = = = = = = = = = = = = = = = 
" 前端开发插件集
" [emmet-vim](https://github.com/mattn/emmet-vim)
" html/xml/css简写语法插件
	let g:user_emmet_mode= 'i'
	let g:user_emmet_install_global= 0
	autocmd FileType html,css EmmetInstall
Plug 'mattn/emmet-vim'

" git管理
Plug 'tpope/vim-fugitive'

" 一些插件只能在linux环境下工作
" 比如：vimspector在gvim中运行会要求带python3特性，即便带py3编译还是存在毛病
" [vimspector](https://github.com/puremourning/vimspector)
execute !has('win32') ? "Plug 'puremourning/vimspector'" : ""
call plug#end()

                                                                                
"                               setting plugins                                 
                                                                                
" drewtempelmeyer/palenight.vim
colorscheme palenight

                                                                                
"                               internal setting                                
                                                                                
" 帮助文档显示行号、相对行号及正常显示字符
" 直接修改$VIMRUNTIME/ftplugin/help.vim文件会在vim版本更新后失效
autocmd FileType help setlocal number relativenumber conceallevel=0 list

                                                                                
"                               external setting                                
                                                                                
" 设置swap目录
let &directory= s:confRoot . 'swap//'
if !isdirectory(&directory)
  call mkdir(&directory)
endif
" 设置undo目录
let &undodir= s:confRoot . 'undoDir'
if !isdirectory(&undodir)
  call mkdir(&undodir)
endif
" 设置帮助文件
let &helpfile= s:confRoot . 'doc' . s:pathSeprator . 'help.cnx'

" keymap file
execute 'source ' . s:confRoot . 'vimrcMAP'
" netrw config
" 这里实现有问题, 应该触发自动命令而非简单条件判断
" if exists("g:loaded_netrwPlugin")
  execute 'source ' . s:confRoot . 'pluginsRC' . s:pathSeprator . 'netrw'
" endif
" coc.nvim config
" 这里需要延时加载或将命令移至其他稍后被加载的文件
" if exists('g:did_coc_loaded') 
  execute 'source ' . s:confRoot . 'pluginsRC' . s:pathSeprator . 'coc'
" endif

                                                                                
"ctags设置
                                                                                
"                                 ctags setting                                 
                                                                                
"一些说明：要使用vim的标签跳转功能必须事先生成对应的标签文件
"linx:
"ctags -R --langmap=c:+.h --languages=c --links=yes --kinds-c=+p \
"-f ~/.vim/ctags /usr/include
"windows:
"暂不设置
" $VIM指向的路径不确定, 可能是配置文件所在目录也可能是vim程序目录
" autocmd FileType c set tags+=$VIM/ctags
" autocmd FileType c execute 'set tags+=' .. (expand('<sfile>:h') . s:pathSeprator . 'ctags')
autocmd FileType c let &tags=&tags . ',' . s:confRoot . 'ctags'
" vim:tabstop=4 noexpandtab
